name: Lint

on:
    workflow_call:
    workflow_dispatch:
    pull_request:
        branches: [master]
        paths:
            - "lua/**"
    push:
        branches: [master]
        paths:
            - "lua/**"

jobs:
    lint:
        runs-on: self-hosted
        steps:
            - name: Install libffi7
              run: sudo apt-get install libffi7

            - name: Checkout
              uses: actions/checkout@v3

            - name: Remove blacklisted
              run: rm -r lua/entities/gmod_wire_expression2/ lua/data lua/wire/gates lua/entities/arthur_mantle/cl_data.lua lua/cap_res_req.lua lua/cap_ver.lua

            - name: GLua Linter
              uses: TASSIA710/action-glua-lint@v1.1.4
              with:
                  lint_doubleNegations: false
                  lint_emptyBlocks: false
                  lint_maxScopeDepth: 99
                  lint_redundantIfStatements: false
                  lint_redundantParentheses: false
                  lint_shadowing: false
                  lint_syntaxErrors: false
                  lint_syntaxInconsistencies: false
                  lint_trailingWhitespace: false
                  lint_unusedLoopVars: false
                  lint_unusedParameters: false
                  lint_unusedVars: false
                  lint_whitespaceStyle: false
